name: continuous build

on: [push, pull_request]

jobs:

  build_arm:
    runs-on: ubuntu-latest
      #strategy:
      #fail-fast: false
      #matrix:
      #  os: [ubuntu-latest]
      #  fortran: [gfortran]
      #  build: [cmake, make]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build arm64 Docker image for release
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64
          #tags: |
          #  ${{ env.IMAGE_NAMESPACE }}/argocd:${{ env.RELEASE_TAG }}-arm64
          #  argoproj/argocd:${{ env.RELEASE_TAG }}-arm64
          #build-args: |
          #  BUILD_ALL_CLIS=false
          #load: true
          #if: ${{ env.DRY_RUN != 'true' }}
     
      #- uses: addnab/docker-run-action@v3
      #  with:
      #    username: tbbharaj
      #    password: tanveen123
          #registry: gcr.io
      #    image: tbbharaj/test-image
      #    run: echo "hello world" 
      #- name: Available platforms
      #  run: sudo apt-get install -y gfortran cmake ccache
      #- name: Get Markupsafe cache
      #  uses: actions/cache@v2
      #  id: markupsafe-cache
      #  with:
      #    path: markupsafe-cache/
      #    key: markupsafe-cache
