name: continuous build

on: [push, pull_request]

jobs:

  build_arm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        fortran: [gfortran]
        build: [cmake, make]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      
      - uses: addnab/docker-run-action@v3
        with:
          username: tbbharaj
          password: tanveen123
          #registry: gcr.io
          image: tbbharaj/test-image
          run: echo "hello world" 
      #- name: Available platforms
      #  run: sudo apt-get install -y gfortran cmake ccache
      #- name: Get Markupsafe cache
      #  uses: actions/cache@v2
      #  id: markupsafe-cache
      #  with:
      #    path: markupsafe-cache/
      #    key: markupsafe-cache
